Error setting username: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error setting password: HTTPConnectionPool(host='localhost', port=35801): Max retries exceeded with url: /session/6ef3217a3f63e0ed1c90c27d83660e02/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b273fd70>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error selecting country: HTTPConnectionPool(host='localhost', port=35801): Max retries exceeded with url: /session/6ef3217a3f63e0ed1c90c27d83660e02/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b2740ef0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error clicking dpp button: HTTPConnectionPool(host='localhost', port=35801): Max retries exceeded with url: /session/6ef3217a3f63e0ed1c90c27d83660e02/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b2741a60>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error clicking login button: HTTPConnectionPool(host='localhost', port=35801): Max retries exceeded with url: /session/6ef3217a3f63e0ed1c90c27d83660e02/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a40b2740e60>: Failed to establish a new connection: [Errno 111] Connection refused'))
