[32mINFO    [0m root:setupMicroplan2.py:61 Navigating to the Microplan creation
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5576990bf0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/aecfe91a73057fdc388f5adbacf04edf
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5576992240>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/aecfe91a73057fdc388f5adbacf04edf
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5576992a20>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/aecfe91a73057fdc388f5adbacf04edf